{{ if .Values.prePuller.enabled -}}
{{ if .Values.rbac.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
roleRef:
  kind: ClusterRole
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
roleRef:
  kind: Role
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  name: pre-puller-{{ .Release.Name }}-{{ .Release.Revision }}
---
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pull-all-nodes-{{ .Release.Time.Seconds }}-{{.Release.Name}}-{{.Release.Revision}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.rbac.enabled }}
      serviceAccountName: pre-puller-{{.Release.Name}}-{{.Release.Revision}}
      {{- end }}
      containers:
        - image: {{ .Values.prePuller.image.name }}:{{ .Values.prePuller.image.tag }}
          args: [{{ .Values.singleuser.image.name | quote }}, {{ .Values.singleuser.image.tag | quote }}]
          name: all-nodes-puller
{{- end }}
